create or replace table layanan (
    id               bigint auto_increment,
    nomor            int,
    tanggal          datetime,
    nomor_surat      varchar(255),
    tanggal_surat    date,
    komunitas        varchar(255),
    nama             varchar(255),
    jenis            int,
    umur             int,
    pekerjaan        varchar(255),
    alamat           varchar(255),
    telepon          varchar(255),
    is_pelayanan     bit,
    is_ideologi      bit,
    is_politik       bit,
    is_sosial        bit,
    is_budaya        bit,
    is_agama         bit,
    is_kamtibmas     bit,
    is_kriminalitas  bit,
    is_tibcar_lantas bit,
    is_prilaku_polri bit,
    is_yan_polri     bit,
    is_lain_lain     bit,
    permasalahan     varchar(1020),
    solusi           varchar(1020),
    id_petugas       varchar(8),
    created_at       datetime,
    created_by       varchar(8),
    updated_at       datetime,
    updated_by       varchar(8),
    is_deleted       bit,
    deleted_at       datetime,
    deleted_by       varchar(8),
    constraint fk_layanan_to_user_01 foreign key (created_by) references user (id),
    constraint fk_layanan_to_user_02 foreign key (updated_by) references user (id),
    constraint fk_layanan_to_user_03 foreign key (deleted_by) references user (id),
    constraint fk_layanan_to_user_04 foreign key (id_petugas) references user (id),
    primary key (id)
) engine = innodb;